name: Latest blog post workflow
on:
schedule:
# Runs every hour
- cron: '0 * * * *'
jobs:
update-readme-with-blog:
name: Update this repo's README with latest blog posts
runs-on: ubuntu-latest
on:
    # Trigger the workflow on push or pull request,
    # but only for the master branch
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
    # Also trigger on page_build, as well as release created events
    page_build:
    release:
      types: # This configuration does not affect the page_build event above
        - created
steps:
  - uses: actions/checkout@v2
  - uses: gautamkrishnar/blog-post-workflow@master
    with:
      feed_list: "https://dev.to/feed/deshanm, https://medium.com/feed/@deshan.m"